version: "3.7"

services:
  api:
    build: 
      context: ./
    ports:
      - 5000:5000
    volumes:
      - ./:/api
    command: flask run --host=0.0.0.0
    working_dir: /api
    environment:
      - FLASK_APP=/api/app.py
      - FLASK_ENV=development
  mongo:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

